/**
 * PARITY SUITE — the guard on running two scoring implementations.
 *
 * The frontend mirrors the Python scoring engines so the SCAN page can
 * recalculate instantly as an analyst edits parameters. That mirror is only
 * defensible if something proves the two agree.
 *
 * `parity-expected.json` is generated by the authoritative Python engine
 * (backend/scripts/emit_parity.py). This suite runs the TypeScript engine
 * over the identical inputs and asserts identical outputs — totals,
 * per-pillar breakdowns, every ledger line's state and contribution, the
 * hard gate, and the coverage-policy verdicts.
 *
 * A FAILURE HERE IS NOT A TEST PROBLEM. It means the browser would show a
 * different score from the one the server records for the same vendor.
 * Fix the divergence; never adjust the expectation.
 *
 * Regenerate after any change to the Python engine:
 *     python3 backend/scripts/emit_parity.py
 */

import { describe, expect, it } from 'vitest'

import expected from './parity-expected.json'
import {
  DEFAULT_POLICY,
  PROTOTYPE_POLICY,
  applyPolicy,
  scoreRisk,
  scoreScan,
  scoreSurveillance,
} from './index'
import type { CheckResult, CheckStatus, PillarKey } from '@/types/domain'

type ScanCase = { input: Record<string, string | null>; expected: Record<string, any> }
type RiskCase = {
  selected: string[]
  checks: Record<string, { status: string; value: string }>
  expected: Record<string, any>
}
type SvCase = { input: Record<string, string | null>; done: boolean; expected: Record<string, any> }
type PolicyCase = { input: Record<string, string | null>; policy: string; expected: Record<string, any> }

const hydrate = (
  raw: Record<string, { status: string; value: string }>,
): Record<string, CheckResult> =>
  Object.fromEntries(
    Object.entries(raw).map(([id, r]) => [
      id,
      { checkId: id, status: r.status as CheckStatus, value: r.value, detail: '' },
    ]),
  )

describe('SCAN parity with the Python engine', () => {
  for (const [name, testCase] of Object.entries(expected.scan as Record<string, ScanCase>)) {
    describe(name, () => {
      const actual = scoreScan(testCase.input)
      const want = testCase.expected

      it('matches the headline totals', () => {
        expect(actual.weighted).toBe(want.weighted)
        expect(actual.best).toBe(want.best)
        expect(actual.pct).toBe(want.pct)
        expect(actual.applicable).toBe(want.applicable)
        expect(actual.tolerance60).toBe(want.tolerance60)
      })

      it('matches the verdict and its coverage note', () => {
        expect(actual.passed).toBe(want.passed)
        expect(actual.verdict).toBe(want.verdict)
        expect(actual.coverageNote).toBe(want.coverageNote)
        expect(actual.assessmentEvaluated).toBe(want.assessmentEvaluated)
      })

      it('matches every pillar breakdown', () => {
        for (const [key, wantPillar] of Object.entries(want.pillars)) {
          const got = actual.pillars[key as PillarKey]
          expect({
            applicable: got.applicable,
            G: got.G,
            Y: got.Y,
            R: got.R,
            positives: got.positives,
            weighted: got.weighted,
            max: got.max,
          }).toEqual(wantPillar)
        }
      })
    })
  }
})

describe('Risk ledger parity with the Python engine', () => {
  for (const [name, testCase] of Object.entries(expected.risk as Record<string, RiskCase>)) {
    describe(name, () => {
      const actual = scoreRisk(hydrate(testCase.checks), testCase.selected)
      const want = testCase.expected

      it('matches the score and band', () => {
        expect(actual.score).toBe(want.score)
        expect(actual.raw).toBe(want.raw)
        expect(actual.band.label).toBe(want.band)
        expect(actual.gained).toBe(want.gained)
        expect(actual.lost).toBe(want.lost)
      })

      it('matches every ledger line, including why it did not participate', () => {
        expect(actual.ledger).toHaveLength(want.ledger.length)
        actual.ledger.forEach((line, i) => {
          const wantLine = want.ledger[i]
          expect(line.id).toBe(wantLine.id)
          expect(line.state).toBe(wantLine.state)
          expect(line.applied).toBe(wantLine.applied)
          expect(line.contribution).toBe(wantLine.contribution)
          expect(line.explanation).toBe(wantLine.explanation)
        })
      })

      it('reports the same number of dead rules', () => {
        expect(actual.dead).toBe(want.dead)
      })
    })
  }
})

describe('Surveillance parity with the Python engine', () => {
  for (const [name, testCase] of Object.entries(
    expected.surveillance as Record<string, SvCase>,
  )) {
    it(name, () => {
      const actual = scoreSurveillance(testCase.input, testCase.done)
      const want = testCase.expected
      expect(actual.done).toBe(want.done)
      expect(actual.applicable).toBe(want.applicable)
      expect(actual.positives).toBe(want.positives)
      expect(actual.pct).toBe(want.pct)
      expect(actual.gateFailed).toBe(want.gateFailed)
      expect(actual.passed).toBe(want.passed)
      expect(actual.verdict).toBe(want.verdict)
      expect(actual.scanValue).toBe(want.scanValue)
    })
  }
})

describe('Coverage policy parity with the Python engine', () => {
  for (const [name, testCase] of Object.entries(
    expected.policy as Record<string, PolicyCase>,
  )) {
    it(name, () => {
      const policy = testCase.policy === 'default' ? DEFAULT_POLICY : PROTOTYPE_POLICY
      const actual = applyPolicy(scoreScan(testCase.input), policy)
      const want = testCase.expected
      expect(actual.verdict).toBe(want.verdict)
      expect(actual.rawVerdict).toBe(want.rawVerdict)
      expect(actual.gated).toBe(want.gated)
      expect(actual.policyVersion).toBe(want.policyVersion)
      expect(actual.reasons).toHaveLength(want.reasonCount)
      expect(actual.headline).toBe(want.headline)
    })
  }
})

describe('the fixtures the client signed off on', () => {
  it('Azahan scores 0.90 / 1.50 at 60.0%', () => {
    const s = scoreScan(expected.scan.azahan.input)
    expect([s.weighted, s.best, s.pct]).toEqual([0.9, 1.5, 60.0])
  })

  it('Meridian scores 3.80 / 3.90 at 97.4%', () => {
    const s = scoreScan(expected.scan.meridian.input)
    expect([s.weighted, s.best, s.pct]).toEqual([3.8, 3.9, 97.4])
  })

  it('Kaveri scores 0.40 / 1.10 at 36.4%', () => {
    const s = scoreScan(expected.scan.kaveri.input)
    expect([s.weighted, s.best, s.pct]).toEqual([0.4, 1.1, 36.4])
  })
})
