"""Initial schema — all 14 tables.

The catalog tables are created empty here; seeding is a separate step
(app/db/seed.py) so that a schema migration and a catalog change are never
entangled. See 0002 for the immutability triggers.

Originally: initial schema

Revision ID: 14f735132247
Revises: 
Create Date: 2026-08-28 11:35:40.778326
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_ts', 'audit_log', ['ts'], unique=False)
    op.create_index('ix_audit_vendor_ts', 'audit_log', ['vendor_id', 'ts'], unique=False)
    op.create_table('catalog_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_versions')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_catalog_versions_content_hash'))
    )
    op.create_table('check_definitions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('feeds_params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('requires', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('cost_paisa', sa.BigInteger(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('screenshots', sa.Integer(), nullable=False),
    sa.Column('needs_company_unlock', sa.Boolean(), nullable=False),
    sa.Column('needs_director_unlock', sa.Boolean(), nullable=False),
    sa.Column('always', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.CheckConstraint("state IN ('active', 'not_configured')", name=op.f('ck_check_definitions_state_enum')),
    sa.CheckConstraint('cost_paisa >= 0', name=op.f('ck_check_definitions_cost_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_definitions'))
    )
    op.create_table('risk_rules',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('needs', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_rules'))
    )
    op.create_table('scan_parameters',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('pillar', sa.String(length=1), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('source_mode', sa.String(length=8), nullable=False),
    sa.Column('feed', sa.Text(), nullable=False),
    sa.Column('fed_by', sa.String(length=32), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("pillar IN ('S', 'C', 'A', 'N')", name=op.f('ck_scan_parameters_pillar_enum')),
    sa.CheckConstraint("source_mode IN ('AUTO', 'HUMAN', 'HOOK')", name=op.f('ck_scan_parameters_source_mode_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_parameters'))
    )
    op.create_table('surveillance_parameters',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('hard_gate', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveillance_parameters'))
    )
    op.create_table('vendors',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('material', sa.Text(), nullable=False),
    sa.Column('spoc', sa.Text(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=False),
    sa.Column('gst', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=12), nullable=True),
    sa.Column('cin', sa.String(length=24), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('surveillance_done', sa.Boolean(), nullable=False),
    sa.Column('selected', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('intake','select','running','manual','scoring','report','review','decided')", name=op.f('ck_vendors_stage_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index('ix_vendors_cin', 'vendors', ['cin'], unique=False)
    op.create_index('ix_vendors_gst', 'vendors', ['gst'], unique=False)
    op.create_index('ix_vendors_pan', 'vendors', ['pan'], unique=False)
    op.create_table('field_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('visited_on', sa.Date(), nullable=True),
    sa.Column('conducted_by', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('gate_failed', sa.Boolean(), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_field_visits_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_visits'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('cin', sa.String(length=24), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('cost_paisa', sa.BigInteger(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name=op.f('ck_jobs_job_status_enum')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_jobs_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('job_id', name=op.f('uq_jobs_job_id'))
    )
    op.create_index('ix_jobs_cin', 'jobs', ['cin', 'requested_at'], unique=False)
    op.create_table('manual_field_templates',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('maps_to', sa.String(length=8), nullable=True),
    sa.Column('map_when', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('hint', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maps_to'], ['scan_parameters.id'], name=op.f('fk_manual_field_templates_maps_to_scan_parameters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_field_templates')),
    sa.UniqueConstraint('maps_to', name='uq_manual_field_templates_maps_to')
    )
    op.create_table('scan_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('param_id', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(length=1), nullable=True),
    sa.Column('set_by', sa.String(length=64), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rating IS NULL OR rating IN ('G','Y','R')", name=op.f('ck_scan_ratings_rating_enum')),
    sa.ForeignKeyConstraint(['param_id'], ['scan_parameters.id'], name=op.f('fk_scan_ratings_param_id_scan_parameters')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_scan_ratings_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_ratings')),
    sa.UniqueConstraint('vendor_id', 'param_id', name='uq_vendor_scan_param')
    )
    op.create_table('surveillance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('param_id', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('observed_by', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['param_id'], ['surveillance_parameters.id'], name=op.f('fk_surveillance_entries_param_id_surveillance_parameters')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_surveillance_entries_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveillance_entries')),
    sa.UniqueConstraint('vendor_id', 'param_id', name='uq_vendor_surveillance_param')
    )
    op.create_table('unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=True),
    sa.Column('cost_paisa', sa.BigInteger(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("scope IN ('company','director')", name=op.f('ck_unlocks_scope_enum')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_unlocks_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unlocks'))
    )
    op.create_index('ix_unlocks_lookup', 'unlocks', ['scope', 'identifier', 'expires_at'], unique=False)
    op.create_table('vendor_check_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('check_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['check_definitions.id'], name=op.f('fk_vendor_check_inputs_check_id_check_definitions')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_check_inputs_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_check_inputs')),
    sa.UniqueConstraint('vendor_id', 'check_id', 'key', name='uq_vendor_check_input')
    )
    op.create_table('vendor_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('check_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('cost_paisa', sa.BigInteger(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pass','warn','fail','skip','unavailable','not_configured','skipped_missing_input')", name=op.f('ck_vendor_checks_status_enum')),
    sa.CheckConstraint('cost_paisa >= 0', name=op.f('ck_vendor_checks_cost_non_negative')),
    sa.ForeignKeyConstraint(['check_id'], ['check_definitions.id'], name=op.f('fk_vendor_checks_check_id_check_definitions')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_checks_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_checks')),
    sa.UniqueConstraint('vendor_id', 'check_id', name='uq_vendor_check')
    )
    op.create_index('ix_vendor_checks_vendor', 'vendor_checks', ['vendor_id'], unique=False)
    op.create_table('vendor_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('catalog_version_id', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('weighted', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('best', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('applicable', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('scan_passed', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('raw_verdict', sa.Text(), nullable=False),
    sa.Column('gated', sa.Boolean(), nullable=False),
    sa.Column('gate_reasons', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('coverage_note', sa.Text(), nullable=False),
    sa.Column('pillars', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.String(length=32), nullable=False),
    sa.Column('risk_ledger', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('risk_dead_rules', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name=op.f('ck_vendor_scores_risk_range')),
    sa.CheckConstraint('weighted <= best', name=op.f('ck_vendor_scores_weighted_within_best')),
    sa.CheckConstraint('weighted >= 0 AND best >= 0', name=op.f('ck_vendor_scores_scan_non_negative')),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], name=op.f('fk_vendor_scores_catalog_version_id_catalog_versions')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_scores_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_scores'))
    )
    op.create_index('ix_vendor_scores_vendor', 'vendor_scores', ['vendor_id', 'computed_at'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('Approved','Conditional','Rejected')", name=op.f('ck_decisions_decision_enum')),
    sa.CheckConstraint('NOT is_override OR (override_reason IS NOT NULL AND length(override_reason) >= 10)', name=op.f('ck_decisions_override_needs_reason')),
    sa.CheckConstraint('length(remarks) >= 10', name=op.f('ck_decisions_remarks_substantive')),
    sa.ForeignKeyConstraint(['score_id'], ['vendor_scores.id'], name=op.f('fk_decisions_score_id_vendor_scores')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_decisions_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_vendor', 'decisions', ['vendor_id'], unique=False)
    op.create_table('vendor_manual_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('template_id', sa.String(length=16), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('entered_by', sa.String(length=64), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['manual_field_templates.id'], name=op.f('fk_vendor_manual_entries_template_id_manual_field_templates')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_manual_entries_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_manual_entries'))
    )
    op.create_index('ix_manual_entries_vendor', 'vendor_manual_entries', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_manual_entries_vendor', table_name='vendor_manual_entries')
    op.drop_table('vendor_manual_entries')
    op.drop_index('ix_decisions_vendor', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_vendor_scores_vendor', table_name='vendor_scores')
    op.drop_table('vendor_scores')
    op.drop_index('ix_vendor_checks_vendor', table_name='vendor_checks')
    op.drop_table('vendor_checks')
    op.drop_table('vendor_check_inputs')
    op.drop_index('ix_unlocks_lookup', table_name='unlocks')
    op.drop_table('unlocks')
    op.drop_table('surveillance_entries')
    op.drop_table('scan_ratings')
    op.drop_table('manual_field_templates')
    op.drop_index('ix_jobs_cin', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('field_visits')
    op.drop_index('ix_vendors_pan', table_name='vendors')
    op.drop_index('ix_vendors_gst', table_name='vendors')
    op.drop_index('ix_vendors_cin', table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('surveillance_parameters')
    op.drop_table('scan_parameters')
    op.drop_table('risk_rules')
    op.drop_table('check_definitions')
    op.drop_table('catalog_versions')
    op.drop_index('ix_audit_vendor_ts', table_name='audit_log')
    op.drop_index('ix_audit_ts', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
